name:  Build With CMake
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: cmake .
    - name: Build
      run: make
      
    - name: Test0
      run: ./Source/tcom -o test1 Test/ForLoop.asm
    - name: Run Test0
      run: ./Source/tvm test1
  